Уровень 2
IllaBulich/MyProject pull request #2
Opened 2022-06-02 07:54 UTC by IllaBulich

@DenVilk

2022-06-02 08:27 UTC, DenVilk requested changes
Внеси требуемые изменения.

2022-06-02 08:27 UTC, DenVilk commented on main.py
> +                if receipts.fio == surname + " " + name + " " + patronymic:
Тут можно использовать f-строку.

2022-06-02 08:27 UTC, DenVilk commented on main.py
> +tasc = Phone(1, 1, 1)
Вынеси обьявление словаря в utils.py.

2022-06-02 16:05 UTC, IllaBulich commented
исправил

2022-06-02 17:36 UTC, IllaBulich commented
@DenVilk

2022-06-02 20:50 UTC, DenVilk requested changes
Инициализация тоже в utils.pu

2022-06-02 20:50 UTC, DenVilk commented on main.py
> +tasc = Phone(1, 1, 1)
Инициализацию также в utils.py :)

2022-06-03 15:27 UTC, IllaBulich commented
дубль №2 @DenVilk

2022-06-05 10:23 UTC, IllaBulich commented
@DenVilk

2022-06-07 14:09 UTC, DenVilk approved these changes
Допущен к следующему уровню

2022-06-07 14:12 UTC, merged